services:
    api:
      container_name: dev_api
      ports: 
        - 3000:3000
      environment: 
        - DB_NAME=projects
        - DB_CONNECTION=mongodb://elwin:5lw9n@db:27017
        - NODE_ENV=development
      depends_on:
        - db
      command: bash -c "npm install && npm run seedDev && npm run dev"
  
    db:
      container_name: dev_db
      volumes:
        - "dbdata:/var/lib/mongodb/data"
      environment: 
        - MONGO_INITDB_ROOT_USERNAME=elwin
        - MONGO_INITDB_DATABASE=projects
        - MONGO_INITDB_ROOT_PASSWORD=5lw9n
  volumes:
    dbdata:
  networks: 
    default:
      name: app_dev